name: ZombiesCore
main: com.thecloud.Core
version: 1.0
commands:
    setspawn:
            description: Sets the spawn.
            usage: /<command>
    spawnpoints:
               description: Adds/removes spawn points.
               usage: /<command>
    setmap:
          description: Sets the server's map.
          usage: /<command>